config/routes.rb
Rails.application.routes.draw do
  get 'pages/index', as: :home

  get 'pages/interact_basic', as: :interact_basic

  get 'pages/interact_advanced', as: :interact_advanced

  get 'pages/references', as: :references

  get 'pages/discussion', as: :discussion

  get 'pages/occ_model', as: :occ_model

  get 'pages/act_emotions', as: :act_emotions

  get 'pages/sw_vignette', as: :sw_vignette

  get 'pages/sw_act_sub_verb_obj', as: :sw_act_sub_verb_obj

  get 'pages/interact_advanced_report', as: :interact_advanced_report

  get 'pages/interact_basic_report', as: :interact_basic_report

  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @active = 'home'
  end

  def interact_basic
    @active = 'interact_basic'
  end

  def interact_advanced
    @active = 'interact_advanced'
  end

  def references
    @active = 'references'
  end

  def discussion
    @active = 'discussion'
  end

  def occ_model
    @active = 'occ_model'
  end

  def act_emotions
    @active = 'act_emotions'
  end

  def sw_vignette
    @active = 'sw_vignette'
  end

  def sw_act_sub_verb_obj
    @active = 'sw_act_sub_verb_obj'
  end

  def interact_advanced_report
    @active = 'interact_advanced'
  end

  def interact_basic_report
    @active = 'interact_basic'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <%= content_for?(:title) ? yield(:title) : "Emotions in OCC and ACT" %>
    </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
        <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

        <!-- For third-generation iPad with high-resolution Retina display: -->
        <!-- Size should be 144 x 144 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

        <!-- For iPhone with high-resolution Retina display: -->
        <!-- Size should be 114 x 114 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

        <!-- For first- and second-generation iPad: -->
        <!-- Size should be 72 x 72 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

        <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
        <!-- Size should be 57 x 57 pixels -->
        <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

        <!-- For all other devices -->
        <!-- Size should be 32 x 32 pixels -->
        <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

        <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "OCC-ACT Comparison", home_path, class:"navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class = "<%= @active == 'home' ? 'active':'' %>">
              <%= link_to "Home", home_path %>
            </li>
            <li class = "<%= @active == 'sw_vignette' ? 'active':'' %>">
              <%= link_to "Steamboat Willie", sw_vignette_path  %>
            </li>
            <li class = "<%= @active == 'occ_model' ? 'active':'' %>">
              <%= link_to "OCC Model", occ_model_path  %>
            </li>
            <li class = "<%= @active == 'act_emotions' ? 'active':'' %>">
              <%= link_to "ACT Emotions", act_emotions_path  %>
            </li>
            <li class = "<%= @active == 'discussion' ? 'active':'' %>">
              <%= link_to "Discussion", discussion_path %>
            </li>
            <li class = "<%= @active == 'interact_basic' ? 'active':'' %>">
              <%= link_to "INTERACT Basic", interact_basic_path  %>
            </li>
            <li class = "<%= @active == 'interact_advanced' ? 'active':'' %>">
              <%= link_to "INTERACT Advance", interact_advanced_path  %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->
    <footer style="margin-top:50px;
                   text-align:center;
                   border-top: 1px solid #e5e5e5;
                   background-color:#f5f5f5;
                   padding: 20px 0;">
      <p>Zeeshan Malik</p>
      <p>University of Waterloo</p>
      <p>z4malik@uwaterloo.ca</p>
    </footer>


  </body>
</html>

app/views/pages/act_emotions.html.erb
<h2 style="text-align:center;margin-bottom:20px;">Emotions in Affect Control Theory</h2>

<div class="col-lg-6">
<p>
Affect Control Theory aims to understand, encode and predict human behavior in social situations. 
It assumes that individuals have and maintain certain identities. These identities are socially 
constructed and people belonging to a certain culture share the meaning of these identities. 
People go into a social setting with presumed identities. Throughout the interaction each 
individual aims to confirm their identity. This goal is mutually respected because if one of the 
interactant's identity is unconfirmed, threatened or compromised it leads to an emotional episode. 
Emotions register the outcome of a social interaction in terms of identity confirmation or 
disconfirmation. 
</p>
<p>
Each identity consists of a set of fundamental sentiments defined in terms of 
Evaluation, Potency, and Activity (EPA). These fundamental sentiments associated with each 
identity, symbols in language used in social interactions, settings and qualitative attributes 
(adjectives) are known as their affective meaning. When two identities interact with each other, 
the affective symbols used in interaction produce a transient impression (feeling) in each 
interactant. These transient impressions may or may not align with the fundamental impressions. 
The difference between transient and fundamental impression related to an identity is known as 
<i>Deflection</i>. <i>Emotion</i> in ACT is the function of this transient impression and resultant
 deflection. If the transient impression happens to be closer to the fundamental sentiment, 
meaning interactants executed a somewhat perfect social behavior, then deflection is negligible 
and both interactants experience <i>Characteristic Emotions</i>. These emotions can also be 
thought of as fundamental emotions associated with a certain identity and are only experienced 
when the concerned identity is confirmed in a social event. They provide as the bases for the 
motivation of socially accepted behavior based on identity confirmation. 
</p>
<p>
<i>Structural Emotions</i> pertain to socially constructed relationships and are experienced when 
identity-confirmation is not fully achieved in a social situation possibly because of opposite 
goals of the interactants to experience ones own characteristic emotions which contradict that of 
the other.
</p>
<p>
<i>Consequent Emotions</i> in ACT are the feelings which are experienced as a result of actual 
behavior of the participant in any event. Although, in essence, all emotions are consequent 
emotions, Characteristic and Structural Emotions provide analytical distinction for 
identity-situated self and social relationships in normative situations. Whereas consequent 
emotions particularly cater for deviant and out-of-character behavior and hence is mostly 
identity disconfirming.
</p>

</div>
<div class="col-lg-6">
<p>
Since emotions in ACT are strictly dependent on Identity, this implies that individuals with 
different identities feel different emotions resulting from objectively same situation.
</p>

<p>
Like most theories of emotions, ACT recognizes behavioral consequences of emotions. But the 
theory differs from conventional wisdom that an emotion begets concomitant emotion-sustaining 
action e.g. anger triggers angry behavior, happiness motivates kind behavior. According to ACT 
when a person experiences an irregular structural/consequent emotion, it <i>informs</i> them that 
the process of identity confirmation is not going well, and in turn their identity 
<i>motivates</i> them to undertake restorative actions in order to experience identity-confirming 
characteristic emotion, rather than showing reaction by emotion-sustaining actions.
</p>

<p>
This kind of restorative action is called <i>Compensatory Behavior</i> as it compensates for the 
out-of-character emotion and is selected to minimize deflection and to move towards 
identity-confirming characteristic emotion. This is the general rule that directs actions of the 
individuals in day-to-day life according to ACT. This rule is only broken when structural 
constraints in a situation or culture in general repeatedly obstruct a person from experiencing 
identity-confirming characteristic emotions through restorative actions. In this case when a 
consequent emotion is endured over a long period of time it turns into a <i>mood</i> and becomes 
integral part of the identity. This in turn leads to <i>Mood-Induced Behavior</i>, which goes 
along with commonsense view of emotions suggesting people always act out their affective mood.
</p>

<p>
Lastly, <i>Emotional Goal-Induced Behavior</i> is the kind of action that an individual 
contemplates or plans to take in future in order to achieve an emotional goal-state. ACT can 
predict actions that will result in emotions specified beforehand. 
</p>

<h3>Important Terms in ACT</h3>
<span class="badge badge-info">Affect</span>
<span class="badge badge-info">Control Principle</span>
<span class="badge badge-info">Identity</span>
<span class="badge badge-info">Identity Confirmation</span>
<span class="badge badge-info">Characteristic Sentiment</span>
<span class="badge badge-info">Transient Sentiment</span>
<span class="badge badge-info">Deflection</span>


<span class="badge badge-info">Characteristic Emotions</span>
<span class="badge badge-info">Structural Emotions</span>
<span class="badge badge-info">Consequent Emotions</span>
<span class="badge badge-info">Identity confirmed -> characteristic emotions of identity</span>
<span class="badge badge-info">
  Identity unconfirmed -> transient impression + deflection: Structural/Consequent Emotions
</span>
<span class="badge badge-info">Transient self and Deflection produce emotion</span>

<span class="badge badge-info">Compensatory Behavior Emotions</span>
<span class="badge badge-info">Mood-induced Behavior</span>
<span class="badge badge-info">Emotional Goal-induced Behavior</span>

<span class="badge badge-info">Emotional Life of a Person</span>
<span class="badge badge-info">private salient high commitment Identity</span>
<span class="badge badge-info">Socially demanded identity</span>

<h3>References</h3>
<ul>
  <li>
    MacKinnon, Neil Joseph. Symbolic interactionism as affect control. SUNY Press, 1994.
    <a href="http://www.amazon.com/Symbolic-Interactionism-Control-Sociology-Emotions/dp/0791420426" target="_blank">Amazon</a>
  </li>
</ul>
</div>

app/views/pages/discussion.html.erb
<h2 style="text-align:center;margin-bottom:20px;">
  OCC Model of Emotions and Affect Control Theory
</h2>
<div class="col-lg-6">
<p>
Why using an animated movie by Disney makes sense for this study? This is because emotions are explicitly displayed in every emotion inducing act. Whereas in shows with humans and real/scripted stories all emotions are not displayed explicitly. A common defensively mechanism and survival strategy by individuals is to hide/snub their emotions.  This leads us to recognize the difference between OCC model of emotions and ACT. OCC model of emotions assumes that emotions occur in specific situations/events and aims to incorporate/encode those situations in its appraisal rules. Due to its emphasis on situationally induced emotions or, so to speak, event driven model, OCC model in turn gives more value to the recognition of emotion at the level of cognition and its subsequent display at physical level and its behavioral implications. Whereas Affect Control Theory basis itself on symbolic interactionism and its derivative Identity Theory which assigns an affective meaning to each symbol (words in a language, in a specific cultural context, describing social identities, personality traits, status and interpersonal acts).
</p>

<p>
Although OCC Model of Emotions integrates Agent in it’s model, which implies that individual is affected by social interaction with agent and object, but assumes that emotional state is a discontinuous function, it has up and down jumps rather than a continuous affective state of person which evolves over a period of time during social interactions. Besides this, human beings are really good at concealing emotions, therefore, if it were not a Disney movie, but a real drama with human characters we could not readily apply OCC model to reveal the emotional states of the characters in it.
</p>
</div>
<div class="col-lg-6">
<p>
On the other hand, Although, Affect Control Theory claims to give precedence to subjective experience, it is not the subjective experience in true sense. It is rather an inter-subjective or rather purported objective social experience. It assumes that individuals should behave in certain ways in particular situations and ignores the adaptability of human beings in certain situations. Rather it only assumes the adaptability in one direction i.e. conformance to social norms and confirmation of constructed identities. It fails to recognize the fact that these socially constructed identities can actually be the cause of emotional inducing situations. People who are not comfortable or fit into their socially constructed identities may not be interested in confirming them, and when their environment imposes it onto them, that would be the actual cause of emotional episode rather than the fact that they they deviated from certain social norm. Nonetheless, it is clear that these socially constructed identities are important part of the social structure, and the way societies and cultures are formed, these are reinforced through social interactions. So the individuals themselves still feel at odds with themselves and that may be the true cause of their emotional episode/experience while they involve into confirming their socially constructed identities to cope with/control/regulate the effect of the environment onto themselves.
</p>

<h3>References</h3>
<ul>
  <li>
    MacKinnon, Neil Joseph. Symbolic interactionism as affect control. SUNY Press, 1994.
    <a href="http://www.amazon.com/Symbolic-Interactionism-Control-Sociology-Emotions/dp/0791420426" target="_blank">Amazon</a>
  </li>
  <li>
    Ortony, Clore and Collins. The Cognitive Structure of Emotions, Cambridge University Press, 1988. 
    <a href="http://www.amazon.ca/Cognitive-Structure-Emotions-Andrew-Ortony/dp/0521386640" target="_blank">Amazon</a>
  </li>
  <li>
    Analysis of Steamboat Willie using OCC Model of Emotions done by J. Hoey
    <a href="https://cs.uwaterloo.ca/~jhoey/SteamboatWillie/OCCSteamboatWillie.html" target="_blank">
      https://cs.uwaterloo.ca/~jhoey/SteamboatWillie/OCCSteamboatWillie.html
    </a>
  </li>
</ul>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h2>Comparing OCC Model of Emotions with ACT's Emotional Predictions on Steamboat Willie, Disney Studio, 1928</h2>

    <p>
      On this site I would present a detailed analysis of Steamboat Willie, a Disney Studio, 1928 movie to compare the emotional predictions of <%= link_to "OCC Model of Emotions", occ_model_path %> with that of <%= link_to "Affect Control Theory (ACT)", "http://www.indiana.edu/~socpsy/ACT/", target: 'blank' %>. It consists of an empirical study to test the idea that many appraisal rules of OCC Model are implicitly encoded in ACT. Similarly to applying OCC rules to movies/books, this project involves labelling the scenes in ACT's subject-verb-object format to see which emotions Interact comes up with. I first converted the Steamboat Willie clip to a <%= link_to "vignette", sw_vignette_path %> and then extracted scenes in form of ACT's subject-verb-object format from it.
    </p>
    <p>
      The hypothesis is that there will be a huge overlap, which would suggest that it may be possible to get rid of many explicit rules, as they kind of emerge from the more general algorithm used in Interact. This hypothesis is confirmed as shown on <%= link_to "INTERACT Basic", interact_basic_path %> and <%= link_to "INTERACT Advance Functions", interact_advanced_path %> pages in scene-by-scene comparison with <%= link_to "OCC Model of Emotion", occ_model_path %>. Although not all the words for emotions in OCC Model match with that of INTERACT's emotional predictions, they more or less convey the same meaning. Moreover ACT is totally dependent on interactants' identities in predicting emotions. This becomes even more complex when INTERACT is used with Advance Functions, in which ACT's predictions are not only dependent on identities of the interactants, but also the setting, attribute and experiencer. I have presented one such scenario on <%= link_to "INTERACT Advance", interact_advanced_path %> page, where I analyze all the events from Mickey the Joyful Worker's perspective in an office setting, where Pete is Mickey's Abusive Boss, Parrot is an Unfriendly Loafer and Minnie is an Affectionate Traveller.
    </p>
    <p>
      I present a brief <%= link_to "discussion", discussion_path %> of OCC Model of Emotion and  Affect Control Theory and why a Disney Studio animation movie is chosen to compare these models in terms of their emotional predictions. I came up with a <%= link_to "vignette for the Steamboat Willie", sw_vignette_path %> and subsequently converted that vignette in a sequence of events in ACT's subject-verb-object format. I used <%= link_to "INTERACT", "http://www.indiana.edu/~socpsy/ACT/interact.htm", target: 'blank' %> to evaluate ACT's emotional predictions for Steamboat Willie scenes.
    </p>
    <p>
      I believe more closer results can be achieved in terms of emotional predictions of OCC model and ACT. Since ACT is sensitive to the setting, assumed and perceived identities along with attributes, one can come up with the optimal configuration for INTERACT to bring ACT prediction closer to that of OCC Model. For example, although Mickey thinks of himself as a Joyful Worker, but when analyzing events from Pete's perspective, Mickey fits the profile of a Lazy Worker and Pete himself could better assume the profile of a Strict Boss. A reasonable overlap is already shown even by only using INTERACT's basic functions, and once the scene have been converted to ACT's sub-verb-obj format, running INTERACT on those sequence of events with different profiles of interactants is a straight forward exercise.
    </p>
    <h3>Acknowledgment:</h3>
    <p>
      I would like to thank
      <a href="https://cs.uwaterloo.ca/~jhoey/" target="_blank">Dr. Jesse Hoey</a> for the
      idea of this study and a very interesting course on
      <a href="https://cs.uwaterloo.ca/~jhoey/teaching/cs886-affect/index.html" target="_blank">
        Affective Computing.
      </a>
      The analysis of Steamboat Willie using OCC Model of Emotions was done and presented in
      one of the lectures for the same course. Please see OCC Model page for the brief discussion on the methodology of driving emotional predictions for OCC Model.
    </p>
    <h3>References:</h3>
    <ul>
      <li>
        MacKinnon, Neil Joseph. Symbolic interactionism as affect control. SUNY Press, 1994.
        <a href="http://www.amazon.com/Symbolic-Interactionism-Control-Sociology-Emotions/dp/0791420426" target="_blank">Amazon</a>
      </li>
      <li>
        Ortony, Clore and Collins. The Cognitive Structure of Emotions, Cambridge University Press, 1988.
        <a href="http://www.amazon.ca/Cognitive-Structure-Emotions-Andrew-Ortony/dp/0521386640" target="_blank">Amazon</a>
      </li>
      <li>
        <a href="http://www.indiana.edu/~socpsy/ACT/interact.htm" target="_blank">
          http://www.indiana.edu/~socpsy/ACT/interact.htm
        </a>
      </li>
    </ul>
  </div>

  <div class="col-lg-4">
    <div class="well sidebar-nav">
      <h3>Zeeshan Malik</h3>
      <ul class="nav nav-list">
        <li><a href="https://uwaterloo.ca" target=_blank>University of Waterloo</a></li>
        <li><a href="mailto:z4malik@uwaterloo.ca">z4malik@uwaterloo.ca</a></li>
      </ul>
    </div><!--/.well -->
  </div><!--/span-->

</div>

app/views/pages/references.html.erb
<h1>Pages#references</h1>
<p>Find me in app/views/pages/references.html.erb</p>

app/views/pages/sw_act_sub_verb_obj.html.erb
<h1>Pages#sw_act_sub_verb_obj</h1>
<p>Find me in app/views/pages/sw_act_sub_verb_obj.html.erb</p>